utils/gdbus:Fix compile conflict
frameworks/utils/gdbus/polkit.c:139: multiple definition of polkit_check_authorization; /external/ofono/ofono/gdbus/polkit.c:157: first defined here

Signed-off-by: yintao <yintao@xiaomi.com>